require('dotenv').config();
const express=require('express'); const path=require('path'); const {Pool}=require('pg');
const app=express();
const pool=new Pool({connectionString:process.env.DATABASE_URL, ssl: process.env.DATABASE_URL?.includes('localhost') ? false : {rejectUnauthorized:false}});
app.use(express.json()); app.use(express.static(path.join(__dirname,'public')));
const etapas=['Entrada / Oportunidade','Entendimento / Briefing','Análise de Viabilidade','Envolvimento de Produtos','Definição / Amostras','Cotação / Custos','Orçamento','Ajustes / Novos Testes','Aprovação do Cliente','Produção / 90 dias','Entrega','Concluído'];
const areas=['Sem pendência','Cliente','Comercial','Produtos','Fornecedor','Compras','PCP / Produção','Outro'];
function codigo(n){return `PRJ-${String(n).padStart(3,'0')}`}
app.get('/api/config',(req,res)=>res.json({etapas,areas,status:['Em andamento','Pausado','Concluído','Cancelado']}));
app.get('/api/indicadores',async(req,res,next)=>{try{const q=await pool.query(`SELECT COUNT(*)::int cadastrados, COUNT(*) FILTER(WHERE status='Em andamento')::int em_andamento, COUNT(*) FILTER(WHERE status='Pausado')::int pausados, COUNT(*) FILTER(WHERE status='Concluído')::int concluidos, COUNT(*) FILTER(WHERE area_pendente='Cliente' AND status NOT IN ('Concluído','Cancelado'))::int aguardando_cliente, COUNT(*) FILTER(WHERE area_pendente='Produtos' AND status NOT IN ('Concluído','Cancelado'))::int aguardando_produtos, COUNT(*) FILTER(WHERE previsao_conclusao<CURRENT_DATE AND status NOT IN ('Concluído','Cancelado'))::int atrasados FROM projetos`);res.json(q.rows[0]);}catch(e){next(e)}});
app.get('/api/projetos',async(req,res,next)=>{try{const q=await pool.query('SELECT * FROM projetos ORDER BY atualizado_em DESC');res.json(q.rows)}catch(e){next(e)}});
app.get('/api/projetos/:id',async(req,res,next)=>{try{const p=await pool.query('SELECT * FROM projetos WHERE id=$1',[req.params.id]);if(!p.rowCount)return res.status(404).json({erro:'Projeto não encontrado'});const h=await pool.query('SELECT * FROM historico_etapas WHERE projeto_id=$1 ORDER BY data_registro DESC',[req.params.id]);res.json({projeto:p.rows[0],historico:h.rows})}catch(e){next(e)}});
app.post('/api/projetos',async(req,res,next)=>{const c=await pool.connect();try{await c.query('BEGIN');const b=req.body;const seq=await c.query('SELECT COALESCE(MAX(id),0)+1 n FROM projetos');const cod=codigo(seq.rows[0].n);const prazo90=b.data_aprovacao?`($12::date + INTERVAL '90 days')::date`:'NULL';const sql=`INSERT INTO projetos(codigo,cliente,segmento,nome,responsavel,data_inicio,previsao_conclusao,status,etapa_atual,area_pendente,proxima_acao,data_aprovacao,prazo_90_dias,observacoes) VALUES($1,$2,$3,$4,$5,COALESCE($6::date,CURRENT_DATE),$7,$8,$9,$10,$11,$12,${prazo90},$13) RETURNING *`;const vals=[cod,b.cliente,b.segmento||null,b.nome,b.responsavel||null,b.data_inicio||null,b.previsao_conclusao||null,b.status||'Em andamento',b.etapa_atual||etapas[0],b.area_pendente||areas[0],b.proxima_acao||null,b.data_aprovacao||null,b.observacoes||null];const p=await c.query(sql,vals);await c.query(`INSERT INTO historico_etapas(projeto_id,etapa,area_pendente,situacao,pendencia_proximo_passo,observacoes) VALUES($1,$2,$3,'Projeto cadastrado',$4,$5)`,[p.rows[0].id,p.rows[0].etapa_atual,p.rows[0].area_pendente,p.rows[0].proxima_acao,'Cadastro inicial']);await c.query('COMMIT');res.status(201).json(p.rows[0]);}catch(e){await c.query('ROLLBACK');next(e)}finally{c.release()}});
app.put('/api/projetos/:id',async(req,res,next)=>{const c=await pool.connect();try{await c.query('BEGIN');const old=await c.query('SELECT * FROM projetos WHERE id=$1',[req.params.id]);if(!old.rowCount){await c.query('ROLLBACK');return res.status(404).json({erro:'Projeto não encontrado'})}const o=old.rows[0],b=req.body;const dataConc=(b.status==='Concluído'&&!o.data_conclusao)?new Date():o.data_conclusao;const q=await c.query(`UPDATE projetos SET cliente=$1,segmento=$2,nome=$3,responsavel=$4,previsao_conclusao=$5,status=$6,etapa_atual=$7,area_pendente=$8,proxima_acao=$9,prazo_proxima_acao=$10,observacoes=$11,data_aprovacao=$12,prazo_90_dias=CASE WHEN $12::date IS NULL THEN NULL ELSE ($12::date + INTERVAL '90 days')::date END,data_conclusao=$13,atualizado_em=NOW() WHERE id=$14 RETURNING *`,[b.cliente,b.segmento||null,b.nome,b.responsavel||null,b.previsao_conclusao||null,b.status,b.etapa_atual,b.area_pendente,b.proxima_acao||null,b.prazo_proxima_acao||null,b.observacoes||null,b.data_aprovacao||null,dataConc,req.params.id]);const mudou=o.status!==b.status||o.etapa_atual!==b.etapa_atual||o.area_pendente!==b.area_pendente||o.proxima_acao!==(b.proxima_acao||null);if(mudou)await c.query(`INSERT INTO historico_etapas(projeto_id,etapa,area_pendente,situacao,pendencia_proximo_passo,observacoes) VALUES($1,$2,$3,$4,$5,$6)`,[req.params.id,b.etapa_atual,b.area_pendente,b.status,b.proxima_acao||null,b.movimentacao_observacao||'Atualização do projeto']);await c.query('COMMIT');res.json(q.rows[0]);}catch(e){await c.query('ROLLBACK');next(e)}finally{c.release()}});
app.use((e,req,res,next)=>{console.error(e);res.status(500).json({erro:'Erro interno',detalhe:process.env.NODE_ENV==='production'?undefined:e.message})});
const PORT=process.env.PORT||3000; app.listen(PORT,()=>console.log(`LENVIE Projetos em http://localhost:${PORT}`));
